### ISSUE TITLE
Error in Heroku (Crash!)

### ISSUE THREAD

**Issue by imatrixgp** [corbindavenport/tootbot#50]
2018-06-27T00:02:48.615048+00:00 app[worker.1]: [ OK ] You have the latest version of Tootbot (2.2)
2018-06-27T00:02:48.615259+00:00 app[worker.1]: [ OK ] Attempting to log in to Twitter...
2018-06-27T00:02:48.900215+00:00 app[worker.1]: [ OK ] Sucessfully authenticated on Twitter as @FortniteBRBest
2018-06-27T00:02:48.900243+00:00 app[worker.1]: [ OK ] cache.csv file not found, created a new one
2018-06-27T00:02:48.900246+00:00 app[worker.1]: [ OK ] Setting up connection with Reddit...
2018-06-27T00:02:49.167314+00:00 app[worker.1]: [ OK ] Getting posts from Reddit...
2018-06-27T00:02:49.471452+00:00 app[worker.1]: [ OK ] media folder not found, created a new one
2018-06-27T00:02:49.513500+00:00 app[worker.1]: Traceback (most recent call last):
2018-06-27T00:02:49.513509+00:00 app[worker.1]:   File "tootbot-heroku.py", line 237, in <module>
2018-06-27T00:02:49.513855+00:00 app[worker.1]:     make_post(post_dict)
2018-06-27T00:02:49.513862+00:00 app[worker.1]:   File "tootbot-heroku.py", line 101, in make_post
2018-06-27T00:02:49.514070+00:00 app[worker.1]:     post_dict[post][2], IMGUR_CLIENT, IMGUR_CLIENT_SECRET)
2018-06-27T00:02:49.514076+00:00 app[worker.1]:   File "/app/getmedia.py", line 154, in get_media
2018-06-27T00:02:49.514314+00:00 app[worker.1]:     img_site = urlopen(img_url)
2018-06-27T00:02:49.514320+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 223, in urlopen
2018-06-27T00:02:49.514651+00:00 app[worker.1]:     return opener.open(url, data, timeout)
2018-06-27T00:02:49.514657+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 532, in open
2018-06-27T00:02:49.515134+00:00 app[worker.1]:     response = meth(req, response)
2018-06-27T00:02:49.515140+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 642, in http_response
2018-06-27T00:02:49.515662+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2018-06-27T00:02:49.515668+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 570, in error
2018-06-27T00:02:49.516183+00:00 app[worker.1]:     return self._call_chain(*args)
2018-06-27T00:02:49.516189+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2018-06-27T00:02:49.516616+00:00 app[worker.1]:     result = func(*args)
2018-06-27T00:02:49.516622+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 650, in http_error_default
2018-06-27T00:02:49.517129+00:00 app[worker.1]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2018-06-27T00:02:49.517193+00:00 app[worker.1]: urllib.error.HTTPError: HTTP Error 429: Too Many Requests
2018-06-27T00:02:49.634982+00:00 heroku[worker.1]: Process exited with status 1
2018-06-27T00:02:49.718158+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by corbindavenport** [comment]
It looks like Imgur is rate-limiting you: https://api.imgur.com/errorhandling

I don't think I can do anything about that. Try reducing the PostLimit, or make a new set of Imgur API keys.
