### ISSUE TITLE
Gfycat retuns 404 error with any URL

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/tootbot#85]
Trying to download any Gfycat link using the official API returns this error:

```
Traceback (most recent call last):
  File "tootbot.py", line 445, in <module>
    make_post(post_dict)
  File "tootbot.py", line 115, in make_post
    hd_media_file = get_hd_media(post_dict[post], IMGUR_CLIENT, IMGUR_CLIENT_SECRET)
  File "D:\GitHub\tootbot\getmedia.py", line 265, in get_hd_media
    gfycat_info = client.query_gfy(gfycat_name)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gfycat\client.py", line 79, in query_gfy
    r.status_code)
```

I've filed a bug with the Gfycat Python library: https://github.com/ankeshanand/py-gfycat/issues/8

In the meantime, Tootbot needs to download Gfycat media without using the API. This Reddit post outlines the URL format: https://www.reddit.com/r/gfycat/comments/3vhl49/did_gfycat_change_its_ui/cxot1ma/

**Comment by corbindavenport** [comment]
After testing a while, it seems like grabbing the URL directly doesn't change anything. Gfycat just throws a 403 error instead of the 404 error the official API provides.

**Downloading media straight from the URL (https://github.com/corbindavenport/tootbot/commit/31dcc0d601a441703f83480d36eef6a5dcdbab87):**

```
[ OK ] Downloading Gfycat at URL https://zippy.gfycat.com/unsungdisgustingdwarfrabbit.gif to media/unsungdisgustingdwarfrabbit.gif
[EROR] File failed to download. Status code: 403
[ OK ] Downloading Gfycat at URL https://giant.gfycat.com/unsungdisgustingdwarfrabbit.mp4 to media/unsungdisgustingdwarfrabbit.mp4
[EROR] File failed to download. Status code: 403
[WARN] Twitter: Skipping a411e9 because non-media posts are disabled or the media file
was not found
[WARN] Mastodon: Skipping a411e9 because non-media posts are disabled or the media file was not found
[ OK ] Sleeping for 600 seconds
```

**Downloading media via the Gfycat library:**

```
[ OK ] Setting up connection with Reddit...
[ OK ] Getting posts from Reddit...
[ OK ] Skipping 3dasau because it is stickied
[ OK ] Skipping a43k42 because it was already posted
Traceback (most recent call last):
  File "tootbot.py", line 449, in <module>
    make_post(post_dict)
  File "tootbot.py", line 112, in make_post
    media_file = get_media(post_dict[post].url, IMGUR_CLIENT, IMGUR_CLIENT_SECRET)
  File "D:\GitHub\tootbot\getmedia.py", line 128, in get_media
    gfycat_info = client.query_gfy(gfycat_name)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gfycat\client.py", line 79, in query_gfy
    r.status_code)
gfycat.error.GfycatClientError: (404) Unable to query for the GIF
```

I assume this is because Gfycat has a newer API that requires authentication, which the official Python library doesn't support (it looks abandoned?). I'll probably have to pull Gfycat data using authenticated JSON directly.

**Comment by corbindavenport** [comment]
The Gfycat library was supposedly updated with support for authentication, so this might be fixable now.

**Comment by marvin8** [comment]
I've created a crude workaround for tootbot to be able to download the mp4 from gfycat.

Basically it involves downloading the gfycat page and then with some rough scraping determining the mp4 download as per below:

```python
response = requests.get(media_url)
    soup = BeautifulSoup(response.text, 'lxml')
    mp4_url = ""
    for tag in soup.find_all("source", src=True):
        src = tag['src']
        if "giant" in src:
            if "mp4" in src:
                mp4_url = src
```

If you'd like I can try creating a PR with my "hack"

**Comment by o3nn** [comment]
> 
> 
> I've created a crude workaround for tootbot to be able to download the mp4 from gfycat.
> 
Hi Marvin! Where do I have to implement this?
