### ISSUE TITLE
Program crash imgur

### ISSUE THREAD

**Issue by dopeytjen** [corbindavenport/tootbot#86]
```
2019-01-02T20:34:42.825228+00:00 app[worker.1]: [ OK ] Getting posts from Reddit...
2019-01-02T20:34:43.428178+00:00 app[worker.1]: [ OK ] Media folder not found, created a new one
2019-01-02T20:34:43.480311+00:00 app[worker.1]: Traceback (most recent call last):
2019-01-02T20:34:43.480321+00:00 app[worker.1]:   File "tootbot-heroku.py", line 301, in <module>
2019-01-02T20:34:43.480823+00:00 app[worker.1]:     make_post(post_dict)
2019-01-02T20:34:43.480830+00:00 app[worker.1]:   File "tootbot-heroku.py", line 106, in make_post
2019-01-02T20:34:43.481080+00:00 app[worker.1]:     media_file = get_media(post_dict[post].url, IMGUR_CLIENT, IMGUR_CLIENT_SECRET)
2019-01-02T20:34:43.481087+00:00 app[worker.1]:   File "/app/getmedia.py", line 168, in get_media
2019-01-02T20:34:43.481287+00:00 app[worker.1]:     img_site = urlopen(img_url)
2019-01-02T20:34:43.481292+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 223, in urlopen
2019-01-02T20:34:43.482350+00:00 app[worker.1]:     return opener.open(url, data, timeout)
2019-01-02T20:34:43.482357+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 532, in open
2019-01-02T20:34:43.482840+00:00 app[worker.1]:     response = meth(req, response)
2019-01-02T20:34:43.482842+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 642, in http_response
2019-01-02T20:34:43.483334+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2019-01-02T20:34:43.483341+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 570, in error
2019-01-02T20:34:43.483930+00:00 app[worker.1]:     return self._call_chain(*args)
2019-01-02T20:34:43.483937+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2019-01-02T20:34:43.484741+00:00 app[worker.1]:     result = func(*args)
2019-01-02T20:34:43.484748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 650, in http_error_default
2019-01-02T20:34:43.485332+00:00 app[worker.1]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2019-01-02T20:34:43.485400+00:00 app[worker.1]: urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Started happening today.

**Comment by corbindavenport** [comment]
I can't find the issue, but I think this was happening for some people months ago, but then it went away. Are you still having this issue?

**Comment by corbindavenport** [comment]
That's good! I'll close this issue, then.
